### ISSUE TITLE
Question regarding Notification Masks

### ISSUE THREAD

**Issue by nicolaspapp** [danielhodson/pyprojfs#1]
Hello there, I have being trying your bindings. Was able to replicate the example with success.  I am having trouble when trying to change the types of notifications I want to get from the OS.
I have been trying a few things, but nothing seems to change it.

Would you mind pointing me in the right direction? What I am looking to do should look similar to this:
```
virtualizationOptions = ProjectedFS.PRJ_STARTVIRTUALIZING_OPTIONS()
virtualizationOptions.NotificationMappingsCount = 0x00000001
virtualizationOptions.NotificationMappings = ( ProjectedFS.PRJ_NOTIFICATION_MAPPING * 1)()        
virtualizationOptions.NotificationMappings[0].NotificationRoot = ""
virtualizationOptions.NotificationMappings[0].NotificationBitMask = ProjectedFS.PRJ_NOTIFY_SUPPRESS_NOTIFICATIONS

# and then pass it to PrjStartVisualizing...

ProjectedFS.PrjStartVirtualizing('some folder', .callbackTable, None, virtualizationOptions, instanceHandle)
```

**Comment by nicolaspapp** [comment]
Looks like there where two typos:
- https://github.com/danielhodson/pyprojfs/blob/master/ProjectedFS.py#L86
- https://github.com/danielhodson/pyprojfs/blob/master/ProjectedFS.py#L73

**Comment by theonlytechnohead** [comment]
Hi @nicolaspapp 
I am trying to do the same thing, how did you resolve your issue? Do you have a working example code now?
Cheers

**Comment by theonlytechnohead** [comment]
I see now, `_fields` should've been `_fields_`

**Comment by nicolaspapp** [comment]
@theonlytechnohead yes indeed. Correcting those typos worked in my case.
